config:
  resourcepack-onplayerjoin: false
download-help-lines:
  - '&aПорядок установки:'
  - '&7- Скачайте ресурпак: &6https://atestacraft.ru/download/resourcepacks/TwitchEmotes.zip'
  - '&7- Скопируйте в папку игры: &6.minecraft/resourcepacks'
  - '&7- Загрузите его в игре: &6Настройки&7>&6Наборы ресурсов...'
  - '&7- Активируйте командой: &6/e on'
  - '&7- Полный список кодов: &6https://gist.github.com/crashmax-off/3e80a443e54b26669dbf8f885e3fd328'
strings:
  plugin-tag: '&6[&2Twitch Emotes&6] &7'
  default-color: '&7'
  shortcut: '&bShortcut: &7'
  noperm: '&cYou dont have permission to use this command!'
  installing: '&7Wait until the installation is completed...'
  installed: '&7Emotes installed with success! Now use &6/e list &7to see all
    available emojis for you.'
  disabling: '&7To see our emotes you need to install fist. We will disable for you!'
  error: '&7Theres an error on install emojis and we will disable for you!'
  emojis:
    enabled: '&aTwitch Emotes enabled for you!'
    disabled: '&cTwitch Emotes disabled for you!'
  setsign:
    usage: '&cUsage: /e setsign <sign line> <text>'
    nolines: '&cThe sign lines need to be from 1 to 4'
    setline-to: '&aAdded text to line {line}: &r{text}&a. Add more lines or click
      on sign to paste the text.'
    no-sign: '&cThis is not a sign!'
  commands:
    install: '&2/{cmd} install &b- &7Temporary install emotes'
    download: '&2/{cmd} download &b- &7Show how to download emotes'
    enable: '&2/{cmd} on/off &b- &7Enable/disable send emotes'
    setsign: '&2/{cmd} setsign <line> <text> &b- &7Edit sign with emotes'
    list: '&2/{cmd} list &b- &7List all emotes available for you'