name: ChatEmotes
main: org.crashmax.ChatEmotes.Emotes
version: 2.0.0
author: CrashMax
softdepend: [ResourcePackApi]
description: Send real Twitch emotes to chat.
commands:
  ChatEmotes:
    description: "Main command for Chat Emotes."
    aliases: [e, emotes]
permissions:
  chatemotes.*:
    description: "All Chat Emotes permissions."
    default: op
    children:
      chatemotes.reload: true
      chatemotes.player: true
  chatemotes.player:
    description: "All player Chat Emotes permissions."
    default: false
    children:
      chatemotes.enable: true
      chatemotes.list: true
      chatemotes.emoji.all: true
      chatemotes.placesign: true
      chatemotes.setsign: true
