name: TwitchEmotes
main: org.crashmax.TwitchEmotes.Emotes
version: 1.1.2
author: CrashMax
softdepend: [ResourcePackApi]
description: Send real Twitch emotes to chat.
commands:
  TwitchEmotes:
    description: "Main command for Twitch Emotes."
    aliases: [e ,emo, emotes]
permissions:
  twitchemotes.*:
    description: "All Twitch Emotes permissions."
    default: op
    children:
      twitchemotes.reload: true
      twitchemotes.player: true
      twitchemotes.setsign: true
  twitchemotes.player:
    description: "All player Twitch Emotes permissions."
    default: false
    children:
      twitchemotes.install: true
      twitchemotes.download: true
      twitchemotes.enable: true
      twitchemotes.list: true
      twitchemotes.emoji.all: true
      twitchemotes.placesign: true