name: TwitchEmotes
main: org.crashmax.TwitchEmotes.Emotes
version: 1.0.0
author: CrashMax
softdepend: [ResourcePackApi]
description: Send real Twitch emotes to chat.
commands:
  MinEmojis:
    description: "Main command for Twitch Emotes."
    aliases: [e ,emo, emotes]
permissions:
  minemojis.*:
    description: "All Twitch Emotes permissions."
    default: op
    children:
      minemojis.reload: true
      minemojis.player: true
      minemojis.setsign: true
  minemojis.player:
    description: "All player Twitch Emotes permissions."
    default: false
    children:
      minemojis.install: true
      minemojis.download: true
      minemojis.enable: true
      minemojis.list: true
      minemojis.emoji.all: true
      minemojis.placesign: true